; NFSHP2 HD Reflections
; Based on NFS HD Reflections by Aero_

[RESOLUTION]
AutoRes = 1                          ; Automatically sets reflection resolution based on display resolution (1080p = 512, 1440p+ = 1024).
CubemapScale = 1.0                   ; Resolution multiplier for vehicle cubemap reflections.
EnviromapScale = 1.0                 ; Resolution multiplier for the composite environment reflection map.
OldGPUCompatibility = 0              ; The cubemap resolution will always be rounded down to the nearest power of two.

[CUSTOM RESOLUTION]
CubemapRes = 512                     ; Resolution of each of the 6 vehicle cubemap face reflections. (128 = Default, 256, 512, 1024, 2048)
EnviromapRes = 512                   ; Resolution of the composite environment reflection map. (128 = Default, 256, 512, 1024, 2048)

[GENERAL]
VehicleReflectionBrightness = 1.0    ; Controls the intensity/brightness of vehicle reflections. (1.0 = Default)
ImproveReflectionLOD = 1             ; Forces high level of detail for vehicle reflections.
